<%@ Page Title="เกี่ยวกับโปรเจ็ค" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="Aioi.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <main aria-labelledby="title">
        <h4><%: Title %>.</h4>
        <br />
        <p>โปรเจ็คนี้พัฒนาขึ้นเพื่อทดสอบทักษะการเขียนภาษา C# .Net Web Application</p>
        <p><span style="color: red; font-weight: bold">ข้อมูลทั้งหมดที่มีอยู่ในระบบ Generated by AI</span> หากไปตรงกับข้อมูลบุคคลใด ขออภัยในที่นี้ด้วย</p>
        <p>ฟังก์ชั่นและการใช้งานอาจไม่ครอบคุม การใช้งานของ User ทั้งหมด เช่น</p>
        <ul>
            <li>Authentication</li>
            <li>Authoraization</li>
       
        </ul> 
    </main> 
</asp:Content>
